version: '3.7'

services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transaction_test_case
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: