= Проект transaction_test_case

Проект transaction_test_case - это приложение для управления транзакциями клиентов и их балансами.

== Использование

Для запуска приложения и базы данных выполните следующие шаги:

1. Установите Docker и Docker Compose.
2. Создайте файл `docker-compose.yml` со следующим содержимым:

[source,yaml]
----
include::docker-compose.yml[]
----

3. Запустите контейнеры Docker с помощью команды `docker-compose up -d`.

4. Подключитесь к базе данных PostgreSQL с помощью следующих параметров:

- Хост: `localhost`
- Порт: `5432`
- Имя пользователя: `postgres`
- Пароль: `postgres`
- Имя базы данных: `transaction_test_case`

5. Примените миграции базы данных с помощью инструмента Goose. Убедитесь, что у вас установлен инструмент Goose. Затем выполните следующую команду в корневой директории проекта:

[source,shell]
----
goose -dir ./migrations postgres "user=postgres password=postgres dbname=transaction_test_case sslmode=disable" up
----

6. Запустите приложение, используя команду `go run cmd/transaction_test_case/main.go`.

7. Теперь вы можете использовать Swagger для взаимодействия с API приложения. Откройте браузер и перейдите по адресу `http://localhost:8080/swagger/index.html`.

== API

API предоставляет следующие ресурсы:

=== Создание клиента

Метод: `POST`
Путь: `/clients/create`

Описание: Создает нового клиента.

Параметры:
- Тело запроса (тип: `rest.CreateClientRequest`) - данные для создания клиента.

Ответ:
- Код 200 (OK) со структурой `rest.CreateClient` - информация о созданном клиенте.

=== Получение баланса клиента

Метод: `POST`
Путь: `/clients/{id}/balance`

Описание: Получает баланс клиента по его идентификатору.

Параметры:
- Путь (тип: `string`, имя: `id`) - идентификатор клиента.

Ответ:
- Код 200 (OK) со структурой `rest.GetBalanceResponse` - информация о балансе клиента.

=== Создание транзакции

Метод: `POST`
Путь: `/transactions/create`

Описание: Создает новую транзакцию для определенного клиента с указанной суммой.

Параметры:
- Тело запроса (тип: `rest.CreateTransactionRequest`) - данные для создания транзакции.

Ответ:
- Код 200 (OK) со структурой `rest.CreateTransactionResponse` - информация о созданной транзакции.

=== Получение статуса транзакции

Метод: `POST`
Путь: `/transactions/{id}`

Описание: Получает статус транзакции по ее идентификатору.

Параметры:
- Путь (тип: `string`, имя: `id`) - идентификатор транзакции.

Ответ:
- Код 200 (OK) со структурой `rest.GetTransactionResponse` - информация о статусе транзакции.
