= Проект transaction_test_case

Проект transaction_test_case - это приложение для управления транзакциями клиентов и их балансами.

== Использование

Для запуска приложения и базы данных выполните следующие шаги:

1. Установите Docker и Docker Compose.

2. Запустите контейнеры Docker с помощью команды `docker-compose up`.

3. Установите переменную окружения DB_CONN со значением postgresql://postgres:postgres@localhost:5432/transaction_test_case?sslmode=disable

4. Примените миграции базы данных с помощью инструмента Goose. Убедитесь, что у вас установлен инструмент Goose. Затем выполните следующую команду в корневой директории проекта:

[source,shell]
----
goose -dir ./migrations postgres "postgresql://postgres:postgres@localhost:5432/transaction_test_case?sslmode=disable" up
----

5. Запустите приложение, используя команду `go run cmd/transaction_test_case/main.go`.

6. Теперь вы можете использовать Swagger для взаимодействия с API приложения. Откройте браузер и перейдите по адресу `http://localhost:8080/swagger/index.html`.

== API

API предоставляет следующие ресурсы:

=== Создание клиента

Метод: `POST`
Путь: `/clients/create`

Описание: Создает нового клиента.

Параметры:
- Тело запроса (тип: `rest.CreateClientRequest`) - данные для создания клиента.

Ответ:
- Код 200 (OK) со структурой `rest.CreateClient` - информация о созданном клиенте.

=== Получение баланса клиента

Метод: `POST`
Путь: `/clients/{id}/balance`

Описание: Получает баланс клиента по его идентификатору.

Параметры:
- Путь (тип: `string`, имя: `id`) - идентификатор клиента.

Ответ:
- Код 200 (OK) со структурой `rest.GetBalanceResponse` - информация о балансе клиента.

=== Создание транзакции

Метод: `POST`
Путь: `/transactions/create`

Описание: Создает новую транзакцию для определенного клиента с указанной суммой.

Параметры:
- Тело запроса (тип: `rest.CreateTransactionRequest`) - данные для создания транзакции.

Ответ:
- Код 200 (OK) со структурой `rest.CreateTransactionResponse` - информация о созданной транзакции.

=== Получение статуса транзакции

Метод: `POST`
Путь: `/transactions/{id}`

Описание: Получает статус транзакции по ее идентификатору.

Параметры:
- Путь (тип: `string`, имя: `id`) - идентификатор транзакции.

Ответ:
- Код 200 (OK) со структурой `rest.GetTransactionResponse` - информация о статусе транзакции.
